variables:
 GLOBAL_MYSECRET: $(dbpwd) # this will not work because the secret variable needs to be mapped as env
 GLOBAL_MY_MAPPED_ENV_VAR: $(dbpwd) # this works because it's not a secret.

steps:

- powershell: |
    Write-Host "Using an input-macro works: $(dbpwd)"
    Write-Host "Using the env var directly does not work: $env:dbpwd"
    Write-Host "Using a global secret var mapped in the pipeline does not work either: $env:GLOBAL_MYSECRET"
    Write-Host "Using a global non-secret var mapped in the pipeline works: $env:GLOBAL_MY_MAPPED_ENV_VAR" 
    Write-Host "Using the mapped env var for this task works and is recommended: $env:MY_MAPPED_ENV_VAR"
  env:
    MY_MAPPED_ENV_VAR: $(dbpwd) # the recommended way to map to an env variable