trigger:
- none

variables:
  myVar1: Prod

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage:
  jobs:
  - job:
    steps:
    - script: echo Testing on Windows $(myVar)

# - stage:
#   jobs:
#   - job:
#     steps:
#     - script: echo Testing on Linux!

