# Starter pipeline
# AUTHOR: Mike Benkovich
# List DevOps projects

# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    az --version
    az extension add -n azure-devops
    echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
    az devops configure --defaults organization=https://NeeleshJain0176.visualstudio.com project="DevOps-Patterns" --use-git-aliases true
    az devops project list --output table

  displayName: 'Show list of projects'
  env:
    AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
